version: "3.9"

services:
    # Database, load from csv with script
    postgres:
      image: postgres
      container_name: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./csvs:/var/lib/postgresql/csvs/
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      expose:
        - "5432"
      networks:
        - backend

    # predict app service
    predict:
      build:
        dockerfile: predict/Dockerfile.predict
        tags:
          - 0.1.0
      container_name: predict
      command: uvicorn app.main:app --host 0.0.0.0
      ports:
        - "8000:8000"
      networks:
        - frontend
      depends_on:
        - postgres

    # bridge straddling 2 networks
    preprocess:
      build:
        dockerfile: preprocess/Dockerfile.preprocess
        tags:
          - 0.1.0
      container_name: preprocess
      command: uvicorn app.main:app --host 0.0.0.0
      env_file:
        - .env
      expose:
        - "8000"
      networks:
        - backend
        - frontend
      depends_on:
        - postgres

networks:
  backend:
    name: backend
  frontend:
    name: frontend
